icon_color: "black"

icon_color_dark:
  default: ""
  type: string
  description: "Optional. Icon color used when the active color scheme is dark. If empty, icon_color is used."

use_platform_colors:
  default: false
  type: bool
  description: "When enabled, each entry in Social links can define its own icon color via 'color' (light) and optionally 'color_dark' (dark). If dark is empty, light is used. If 'color' is empty, it falls back to the global icon color."

social_links:
  type: objects
  default:
    - id: email
      enabled: true
      label: Email
      user_field: Email
      icon: envelope
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: email
      base_url: ""
      allowed_hosts: ""
      path_regex: ""

    - id: facebook
      enabled: true
      label: Facebook
      user_field: Facebook
      icon: fab-facebook
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://www.facebook.com/"
      allowed_hosts: "facebook.com,www.facebook.com,m.facebook.com"
      path_regex: ""

    - id: instagram
      enabled: true
      label: Instagram
      user_field: Instagram
      icon: fab-instagram
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://www.instagram.com/"
      allowed_hosts: "instagram.com,www.instagram.com"
      path_regex: ""

    - id: threads
      enabled: true
      label: Threads
      user_field: Threads
      icon: fab-threads
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://www.threads.net/@"
      allowed_hosts: "threads.net,www.threads.net"
      path_regex: ""

    - id: x
      enabled: true
      label: X
      user_field: Twitter
      icon: fab-twitter
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://twitter.com/"
      allowed_hosts: "twitter.com,www.twitter.com,x.com,www.x.com"
      path_regex: ""

    - id: linkedin
      enabled: true
      label: LinkedIn
      user_field: LinkedIn Profile
      icon: fab-linkedin-in
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: url_locked
      base_url: ""
      allowed_hosts: "linkedin.com,www.linkedin.com"
      path_regex: "^/(in|company|school|pub)/[^/?#]+/?$"

    - id: youtube
      enabled: true
      label: YouTube
      user_field: Youtube
      icon: fab-youtube
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://youtube.com/@"
      allowed_hosts: "youtube.com,www.youtube.com"
      path_regex: ""

    - id: tiktok
      enabled: true
      label: TikTok
      user_field: Tiktok
      icon: fab-tiktok
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://tiktok.com/@"
      allowed_hosts: "tiktok.com,www.tiktok.com"
      path_regex: ""

    - id: telegram
      enabled: true
      label: Telegram
      user_field: Telegram
      icon: fab-telegram
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://t.me/"
      allowed_hosts: "t.me"
      path_regex: ""

    - id: github
      enabled: true
      label: GitHub
      user_field: Github
      icon: fab-github
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://github.com/"
      allowed_hosts: "github.com,www.github.com"
      path_regex: ""

    - id: bluesky
      enabled: true
      label: Bluesky
      user_field: Bluesky
      icon: fab-bluesky
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://bsky.app/profile/"
      allowed_hosts: "bsky.app,www.bsky.app"
      path_regex: ""

    - id: strava
      enabled: true
      label: Strava
      user_field: Strava
      icon: fab-strava
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: numeric_id
      base_url: "https://strava.com/athletes/"
      allowed_hosts: "strava.com,www.strava.com"
      path_regex: "^/athletes/\\d+"

    - id: twitch
      enabled: true
      label: Twitch
      user_field: Twitch
      icon: fab-twitch
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://www.twitch.tv/"
      allowed_hosts: "twitch.tv,www.twitch.tv"
      path_regex: ""

    - id: soundcloud
      enabled: true
      label: Soundcloud
      user_field: Soundcloud
      icon: fab-soundcloud
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://soundcloud.com/"
      allowed_hosts: "soundcloud.com,www.soundcloud.com"
      path_regex: ""

    - id: spotify
      enabled: true
      label: Spotify
      user_field: Spotify
      icon: fab-spotify
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: url_locked
      base_url: ""
      allowed_hosts: "open.spotify.com"
      path_regex: "^(?:/(?:artist|track|album|playlist|show|episode)/[A-Za-z0-9]+|/user/[^/?#]+(?:/playlist/[A-Za-z0-9]+)?)\/?$"

    - id: bandcamp
      enabled: true
      label: Bandcamp
      user_field: Bandcamp
      icon: fab-bandcamp
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: url_locked
      base_url: ""
      allowed_hosts: ".bandcamp.com,bandcamp.com,www.bandcamp.com"
      path_regex: ""

    - id: steam
      enabled: true
      label: Steam
      user_field: Steam
      icon: fab-steam
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: url_locked
      base_url: ""
      allowed_hosts: "steamcommunity.com,www.steamcommunity.com"
      path_regex: "^/(id|profiles)/[^/?#]+/?$"

    - id: mastodon
      enabled: true
      label: Mastodon
      user_field: Mastodon
      icon: fab-mastodon
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: url_any_https
      base_url: ""
      allowed_hosts: ""
      path_regex: ""

    - id: tumblr
      enabled: true
      label: Tumblr
      user_field: Tumblr
      icon: fab-tumblr
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://www.tumblr.com/"
      allowed_hosts: "tumblr.com,www.tumblr.com,.tumblr.com"
      path_regex: ""

    - id: discord_profile
      enabled: true
      label: Discord (profile)
      user_field: Discord
      icon: fab-discord
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: numeric_id
      base_url: "https://discord.com/users/"
      allowed_hosts: "discord.com,www.discord.com,discordapp.com,www.discordapp.com"
      path_regex: "^/users/\\d+"

    - id: onlyfans
      enabled: true
      label: OnlyFans
      user_field: OnlyFans
      icon: globe
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://onlyfans.com/"
      allowed_hosts: "onlyfans.com,www.onlyfans.com"
      path_regex: ""

    - id: fansly
      enabled: true
      label: Fansly
      user_field: Fansly
      icon: globe
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://fansly.com/"
      allowed_hosts: "fansly.com,www.fansly.com"
      path_regex: ""

    - id: fetlife
      enabled: true
      label: FetLife
      user_field: FetLife
      icon: globe
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: numeric_id
      base_url: "https://fetlife.com/users/"
      allowed_hosts: "fetlife.com,www.fetlife.com"
      path_regex: "^/users/\\d+"

    - id: fancentro
      enabled: true
      label: FanCentro
      user_field: FanCentro
      icon: globe
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://fancentro.com/"
      allowed_hosts: "fancentro.com,www.fancentro.com"
      path_regex: ""

    - id: linktree
      enabled: true
      label: Linktree
      user_field: Linktree
      icon: link
      icon_image: ""
      icon_mask: ""
      badge_background: ""
      badge_background_dark: ""
      badge_radius: ""
      color: ""
      color_dark: ""
      input_type: handle
      base_url: "https://linktr.ee/"
      allowed_hosts: "linktr.ee,www.linktr.ee"
      path_regex: ""
  schema:
    name: social_link
    identifier: id
    properties:
      id:
        type: string
      enabled:
        type: boolean
      label:
        type: string
      user_field:
        type: string
      icon:
        type: string
      icon_image:
        type: string
      icon_mask:
        type: string
      badge_background:
        type: string
      badge_background_dark:
        type: string
      badge_radius:
        type: string
      color:
        type: string
      color_dark:
        type: string
      input_type:
        type: enum
        choices:
          - handle
          - numeric_id
          - email
          - url_locked
          - url_any_https
      base_url:
        type: string
      allowed_hosts:
        type: string
      path_regex:
        type: string

svg_icons:
  default: "user|globe|link|envelope|fab-twitter|fab-facebook|fab-linkedin-in|fab-instagram|fab-threads|fab-youtube|fab-discord|fab-steam|fab-twitch|fab-bandcamp|fab-spotify|fab-soundcloud|fab-tiktok|fab-telegram|fab-mastodon|fab-bluesky|fab-github|fab-strava|fab-tumblr"
  type: list
  description: "Required: icons that are not part of Discourse's default SVG sprite must be listed here, otherwise they won't render (e.g. Discord)."
